### ISSUE TITLE
Week 4:

### ISSUE THREAD

**Issue by PrishaB** [PrishaB/Individual_Repo2.0#5]
Grader: Anika
Final Score: 5/5

[Study Plan](https://prishab.github.io/Individual_Repo2.0/studyplan)

[Create Task](https://github.com/PrishaB/Individual_Repo2.0/blob/main/docs/create_task.md) 
- Code/Runtime
- Write up
- Video

[Team Work/Login](https://github.com/PrishaB/n224_Venus-1-)
- Start or add to existing project
- All three hacks up and running
- Analysis Done (check wiki)

**Comment by anika1sharma1** [comment]
Final Score: 5/5

CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [x] Analysis: the [csp.nighthawkcodingsociety.com](http://csp.nighthawkcodingsociety.com/) implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [x] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack #2 Add logout to CRUD screen
- [x] Hack #3 Add login_required to another portion of the project
